version: '2'

services:
  workspace:
    container_name: dockerhero_workspace
    image: johanvanhelden/dockerhero-workspace:latest
    volumes:
      - ./crons:/var/crons
      - ./databases:/var/www/databases
      - ./.phpredisadmin:/var/www/phpredisadmin
      - ./../projects/:/var/www/projects
    #environment:
    #  - NODE_VERSION=root
    tty: true
    dns: 8.8.8.8

  php:
    container_name: dockerhero_php
    image: johanvanhelden/dockerhero-php-7.3-fpm:latest
    links:
      - db
      - workspace
      - redis
    volumes_from:
      - workspace
    dns: 8.8.8.8
    ports:
      - "9912:9912"

#  php:
#      build: ./docker/php73special
#      container_name: koel_php
#    links:
#      - db
#      - workspace
#      - redis
#    volumes_from:
#      - workspace
#    depends_on:
#        - db
#    env_file: .env
#    ports:
#        - '8000:80'
#    volumes:
#        - '~/Music:/home/koel/media'
#        - '.env:/var/www/html/.env'

  web:
    container_name: dockerhero_web
    image: johanvanhelden/dockerhero-nginx:latest
    links:
      - php
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/dockerhero/custom
      - nginx_logs:/var/log/nginx
    volumes_from:
      - php
      - workspace
    ports:
      - "80:80"
      - "443:443"
    dns: 8.8.8.8

  db:
    container_name: dockerhero_db
    image: mysql:5.6
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - "database:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: koel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    dns: 8.8.8.8

  redis:
    container_name: dockerhero_redis
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes


### phpMyAdmin ###########################################
  phpmyadmin:
    container_name: dockerhero_myadmin
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - "db"
    volumes:
      - ./docker/phpmyadmin/themes/metro/:/var/www/html/themes/metro/

volumes:
  database:
    driver: "local"
  nginx_logs:
    driver: "local"
  redis:
    driver: "local"
